### Exercice 1:

Write a function that takes a string, and two indexes (integers), and returns a slice of that string as well as the length of the string.
Call the function, and store the results in two variables

In [24]:
#Declare the function
def slice(str,a,b):
    return str[a:b],len(str[a:b])
    
#Call the function
str="test"
res=slice(str,1,3)

#print the result in a well formated format
print("sliced string:",res[0])
print("lenght of sliced string:",res[1])

sliced string: es
lenght of sliced string: 2


### Exercice 2:

1. Write a function that takes two arguments, and returns the sum of the two.
2. Call the function with the values 1 and 2.1, then check the type of the result.
3. Call the function with the values False and 2, then check the type of the result.

In [25]:
#Declare the function
def sum(a,b):
    return a+b

#Call with the values 1 and two
print(sum(1,2.1))
print(sum(1,False))

#Check the type of the result
print(type(sum(1,2.1)))
print(type(sum(1,False)))


3.1
1
<class 'float'>
<class 'int'>


### Exercice 3:

Write a function that takes a string and returns a dictionary containing character frequency.

*example*

    string sample: 'test'
    
    expected result: {'t':2, 'e':1, 's':1}

In [28]:
#Declare the function
def freq(str):
    d = {}
    for i in range (len(str)):
        d[str[i]]=str.count(str[i])
    return d

#Print the result
freq("test")

{'t': 2, 'e': 1, 's': 1}

### Exercice 4:

Given two lists, iterate both lists simultaniously, such the first list would display item in original order and the second list in reverse order

*example*:

In [ ]:
from lib import print_orl #this is a lib you dont have access to
print_orl([1,2,3],[1,2,3])

In [35]:
#...
def rev(K,L):
    L.reverse()
    for i in range (len(L)):
        print(K[i],L[i])

rev([1,2,3],[1,2,3])

1 3
2 2
3 1


### Exercice 5:

Given two 2d arrays, stack them horizontally.

*example:*

In [29]:
import numpy as np

#The input
a = np.ones((1, 10)).reshape(2, -1)
b = np.zeros((1, 10)).reshape(2, -1)

#Try to print input
#...
#print(a)
#print(b)

#concatenate horizontally
#output shoul look like:     array([[1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
#                                   [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.]])

c=np.vstack([np.concatenate([a[0], b[0]]),np.concatenate([a[1], b[1]])])
print(c)


[[1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]]


### exercice 6:

In [ ]:

# 3-dimensional array
a= np.array([[[ 0,  1,  2],
                     [ 3,  4,  5],
                     [ 6,  7,  8]],
  
                    [[ 9, 10, 11],
                     [12, 13, 14],
                     [15, 16, 17]],
 
                    [[18, 19, 20],
                     [21, 22, 23],
                     [24, 25, 26]]])

Create the following patterns using the bellow arrays a and b, and numpy functions:

In [33]:
a = np.arange(3)
b = np.ones((3,3,3))

#print(a)
#print(b)

#output1 the following array: array([0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2])
#...
for i in range(3):
    b[1][i]=i
print(b)
#output2 the follwing array: array([[[1., 2., 3.],
#                                    [1., 2., 3.],
#                                    [1., 2., 3.]],

#                                    [[1., 2., 3.],
#                                    [1., 2., 3.],
#                                    [1., 2., 3.]],

#                                    [[1., 2., 3.],
#                                    [1., 2., 3.],
#                                    [1., 2., 3.]]])



#output3 array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
#                [1., 1., 1., 1., 1., 1., 1., 1., 1.],
#                [1., 1., 1., 1., 1., 1., 1., 1., 1.]])



[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [1. 1. 1.]
  [2. 2. 2.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
